//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanoBatteryTest.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NanoBatteryTest.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to УСТАНОВИТЬ.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СТЕНД ИСПЫТАНИЯ АККУМУЛЯТОРНЫХ БАТАРЕЙ.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПЕРЕДОВЫЕ ИССЛЕДОВАНИЯ И ТЕХНОЛОГИИ.
        /// </summary>
        internal static string Art {
            get {
                return ResourceManager.GetString("Art", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НАЗАД.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ТОК БАТАРЕИ, А.
        /// </summary>
        internal static string BatCurrent {
            get {
                return ResourceManager.GetString("BatCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СОСТОЯНИЕ БАТАРЕИ.
        /// </summary>
        internal static string BattertyParameters {
            get {
                return ResourceManager.GetString("BattertyParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to МОДИФИЦИРОВАННАЯ.
        /// </summary>
        internal static string BatteryUsingCNM {
            get {
                return ResourceManager.GetString("BatteryUsingCNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to МОДИФИЦИРОВАННАЯ БАТАРЕЯ.
        /// </summary>
        internal static string BatteryWithCNMTitle {
            get {
                return ResourceManager.GetString("BatteryWithCNMTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НАЧАЛО.
        /// </summary>
        internal static string Begin {
            get {
                return ResourceManager.GetString("Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СРАВНЕНИЕ СТАДИЙ ЗАРЯДА.
        /// </summary>
        internal static string ChargeCompareChartTitle {
            get {
                return ResourceManager.GetString("ChargeCompareChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СТАДИЯ ЗАРЯДА БАТАРЕИ.
        /// </summary>
        internal static string ChargeCycle {
            get {
                return ResourceManager.GetString("ChargeCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длительность заряда.
        /// </summary>
        internal static string ChargeDurationHeader {
            get {
                return ResourceManager.GetString("ChargeDurationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПРЕВЫШЕНО ДОПУСТИМОЕ ВРЕМЯ ЗАРЯДА БАТАРЕИ.
        /// </summary>
        internal static string ChargeTimeout {
            get {
                return ResourceManager.GetString("ChargeTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заряд, Ah.
        /// </summary>
        internal static string ChargeValueHeader {
            get {
                return ResourceManager.GetString("ChargeValueHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ТОК, A.
        /// </summary>
        internal static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ТОК, A.
        /// </summary>
        internal static string CurrentAxisTitle {
            get {
                return ResourceManager.GetString("CurrentAxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДОСТИГНУТ ПРЕДЕЛ ТОКА ЗАРЯДКИ.
        /// </summary>
        internal static string CurrentStabilityRecived {
            get {
                return ResourceManager.GetString("CurrentStabilityRecived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № Цикла.
        /// </summary>
        internal static string CycleNoHeader {
            get {
                return ResourceManager.GetString("CycleNoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СОЕДИНЕНИЕ С УСТРОЙСТВАМИ КОНТРОЛЯ И СБОРА ИНФОРМАЦИИ.
        /// </summary>
        internal static string DevConnectionIformation {
            get {
                return ResourceManager.GetString("DevConnectionIformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПРОМЫШЛЕННАЯ СЕТЬ.
        /// </summary>
        internal static string DevConnectionTitle {
            get {
                return ResourceManager.GetString("DevConnectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СТАДИЯ РАЗРЯДА БАТАРЕИ.
        /// </summary>
        internal static string DischargeCycle {
            get {
                return ResourceManager.GetString("DischargeCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длительность разряда.
        /// </summary>
        internal static string DischargeDurationHeader {
            get {
                return ResourceManager.GetString("DischargeDurationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разряд, Ah.
        /// </summary>
        internal static string DischargeValueHeader {
            get {
                return ResourceManager.GetString("DischargeValueHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СРАВНЕНИЕ СТАДИЙ РАЗРЯДА.
        /// </summary>
        internal static string DishargeCompareChartTitle {
            get {
                return ResourceManager.GetString("DishargeCompareChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЭЛЕКТРОНИКА АСУ:.
        /// </summary>
        internal static string ElectricDesigner {
            get {
                return ResourceManager.GetString("ElectricDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЧЕРВЯК А.Г..
        /// </summary>
        internal static string ElectricDesignerNames {
            get {
                return ResourceManager.GetString("ElectricDesignerNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОШИБКА.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВЫХОД.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЯЗЫК.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СООБЩЕНИЯ.
        /// </summary>
        internal static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СООБЩЕНИЯ СИСТЕМЫ.
        /// </summary>
        internal static string MessagesTitle {
            get {
                return ResourceManager.GetString("MessagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to МИНСК, БЕЛАРУСЬ.
        /// </summary>
        internal static string MinskBelarus {
            get {
                return ResourceManager.GetString("MinskBelarus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПРОВЕРКА СВЯЗИ С УСТРОЙСТВАМИ УПРАВЛЕНИЯ И СБОРА ИНФОРМАЦИИ.
        /// </summary>
        internal static string MsgConnectionToDevice {
            get {
                return ResourceManager.GetString("MsgConnectionToDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОШИБКА СОЕДИНЕНИЯ С УСТРОЙСТВОМ {0} ПО АДРЕСУ {1}.
        /// </summary>
        internal static string MsgDeviceConnectionFailed {
            get {
                return ResourceManager.GetString("MsgDeviceConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to УСТРОЙСТВО  {0} ПО АДРЕСУ {1} БЫЛО ЗАПУЩЕНО.
        /// </summary>
        internal static string MsgDeviceStarted {
            get {
                return ResourceManager.GetString("MsgDeviceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВЫ ХОТИТЕ ЗАКРЫТЬПРИЛОЖЕНИЕ?.
        /// </summary>
        internal static string MsgExitApplication {
            get {
                return ResourceManager.GetString("MsgExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВЫ ДЕЙСТВИТЕЛЬНО ХОТИТЕ ПРЕРВАТЬ ИСПЫТАНИЯ?.
        /// </summary>
        internal static string MsgStopExperiment {
            get {
                return ResourceManager.GetString("MsgStopExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДЕТАЛИ ИСПЫТАНИЯ.
        /// </summary>
        internal static string OperationDetails {
            get {
                return ResourceManager.GetString("OperationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВРЕМЯ ПРОСТОЯ ПОСЛЕ ЗАРЯДА.
        /// </summary>
        internal static string ParAfterchargeRelaxation {
            get {
                return ResourceManager.GetString("ParAfterchargeRelaxation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПАРАМЕТРЫ ТЕСТИРОВАНИЯ.
        /// </summary>
        internal static string ParametersTitle {
            get {
                return ResourceManager.GetString("ParametersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕМКОСТЬ БАТАРЕИ, Ah.
        /// </summary>
        internal static string ParBatteryCapacity {
            get {
                return ResourceManager.GetString("ParBatteryCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПРЕДЕЛ НАПРЯЖЕНИЯ ПРИ ЗАРЯДЕ, В.
        /// </summary>
        internal static string ParBatteryHighVoltageLimit {
            get {
                return ResourceManager.GetString("ParBatteryHighVoltageLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПРЕДЕЛ НАПРЯЖЕНИЯ ПРИ РАЗРЯДЕ, В.
        /// </summary>
        internal static string ParBatteryLowVoltageLimit {
            get {
                return ResourceManager.GetString("ParBatteryLowVoltageLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПРЕДЕЛЬНОЕ ВРЕМЯ ЗАРЯДА.
        /// </summary>
        internal static string ParChargeTimeout {
            get {
                return ResourceManager.GetString("ParChargeTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НАПРЯЖЕНИЯ ЗАРЯДА, В.
        /// </summary>
        internal static string ParChargeVoltage {
            get {
                return ResourceManager.GetString("ParChargeVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЗАРЯДКА ПРИ ОКОНЧАНИИ.
        /// </summary>
        internal static string ParChargeWhenComplete {
            get {
                return ResourceManager.GetString("ParChargeWhenComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОГРАНИЧЕНИЕ ТОКА ПРИ ЗАРЯДКЕ, %.
        /// </summary>
        internal static string ParCurrentPercentsLimit {
            get {
                return ResourceManager.GetString("ParCurrentPercentsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОКНО ВЫРАВНИВАНИЯ ТОКА.
        /// </summary>
        internal static string ParCurrentStability {
            get {
                return ResourceManager.GetString("ParCurrentStability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КОЛИЧЕСТВО ЦИКЛОВ.
        /// </summary>
        internal static string ParCycleCount {
            get {
                return ResourceManager.GetString("ParCycleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НАЧИНАТЬ С ЗАРЯДА.
        /// </summary>
        internal static string ParStartFrom {
            get {
                return ResourceManager.GetString("ParStartFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИСТОЧНИК ПИТАНИЯ.
        /// </summary>
        internal static string PowerSource {
            get {
                return ResourceManager.GetString("PowerSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to РЕВЕРС.
        /// </summary>
        internal static string PowerSourceReverse {
            get {
                return ResourceManager.GetString("PowerSourceReverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to РАБОТА.
        /// </summary>
        internal static string PowerSourceSwitch {
            get {
                return ResourceManager.GetString("PowerSourceSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to РАЗРАБОТЧИК ПО :.
        /// </summary>
        internal static string ProgrammDesigner {
            get {
                return ResourceManager.GetString("ProgrammDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to МАТВЕЙЧИК Е.А..
        /// </summary>
        internal static string ProgrammDesignerNames {
            get {
                return ResourceManager.GetString("ProgrammDesignerNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ТОК ИП, А.
        /// </summary>
        internal static string PSCurrent {
            get {
                return ResourceManager.GetString("PSCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОЖИДАНИЕ ПЕРЕД ЦИКЛОМ РАЗРЯДА.
        /// </summary>
        internal static string RelaxCycle {
            get {
                return ResourceManager.GetString("RelaxCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СОХРАНИТЬ.
        /// </summary>
        internal static string SaveData {
            get {
                return ResourceManager.GetString("SaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЭТАЛОННАЯ.
        /// </summary>
        internal static string SingleBattery {
            get {
                return ResourceManager.GetString("SingleBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЭТАЛОННАЯ БАТАРЕЯ.
        /// </summary>
        internal static string SingleBatteryTitle {
            get {
                return ResourceManager.GetString("SingleBatteryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to РАБОТА.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СТОП.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ТЕХНОЛОГИ :.
        /// </summary>
        internal static string Tehnologists {
            get {
                return ResourceManager.GetString("Tehnologists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ШУШКОВ С.В., КРАУКЛИС А.В..
        /// </summary>
        internal static string TehnologistsNames {
            get {
                return ResourceManager.GetString("TehnologistsNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВРЕМЯ.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВРЕМЯ.
        /// </summary>
        internal static string TimeAxisTitle {
            get {
                return ResourceManager.GetString("TimeAxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception detect : {0}.
        /// </summary>
        internal static string UnhandledExceptionMessage {
            get {
                return ResourceManager.GetString("UnhandledExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НАПРЯЖЕНИЕ, В.
        /// </summary>
        internal static string Voltage {
            get {
                return ResourceManager.GetString("Voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НАПРЯЖЕНИЕ, В.
        /// </summary>
        internal static string VoltageAxisTitle {
            get {
                return ResourceManager.GetString("VoltageAxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПРЕДЕЛ НАПРЯЖЕНИЯ БАТАРЕИИ {0}.
        /// </summary>
        internal static string VoltageLimitRecived {
            get {
                return ResourceManager.GetString("VoltageLimitRecived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОЖИДАНИЕ ДЕЙСТВИЙ ПОЛЬЗОВАТЕЛЯ.
        /// </summary>
        internal static string WaitingUser {
            get {
                return ResourceManager.GetString("WaitingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стенд испытания аккумуляторных батарей разработан для тестирования добавок углеродных наноматериалов в электролит . .
        /// </summary>
        internal static string WelcomeIformation {
            get {
                return ResourceManager.GetString("WelcomeIformation", resourceCulture);
            }
        }
    }
}
